// Generated by Hive CE
// Do not modify
// Check in to version control

import 'package:hive_ce/hive_ce.dart';
import 'package:walt/data/models/walt_category.dart';

extension HiveRegistrar on HiveInterface {
  void registerAdapters() {
    registerAdapter(WaltCategoryAdapter());
  }
}

extension IsolatedHiveRegistrar on IsolatedHiveInterface {
  void registerAdapters() {
    registerAdapter(WaltCategoryAdapter());
  }
}
